### ISSUE TITLE
Error al agregar [HttpGet("{nombre}")

### ISSUE THREAD

**Issue by inghasanchez** [gavilanch/CursoRESTfulAPIsASPNETCore#11]
[WebApiAutoresArmando.zip](https://github.com/gavilanch/CursoRESTfulAPIsASPNETCore/files/8995016/WebApiAutoresArmando.zip)
Buen dia,
Aqui se encuentra mi proyecto de Autores.
Saludos.

**Comment by gavilanch** [comment]
Buenas, ya te respondí por Udemy.
Saludos!
