### ISSUE TITLE
Favor regalame el link del fuente del video  10 - Hola mundo Web API y Visual Studio

### ISSUE THREAD

**Issue by henrypandales** [gavilanch/CursoRESTfulAPIsASPNETCore#5]
10 - Hola mundo Web API y Visual Studio | Preparando el Ambiente de Desarrollo
https://www.youtube.com/watch?v=ZBtunhmxcCM

**Comment by henrypandales** [comment]
Me puedes escribir al whatsapp +573147754208

**Comment by gavilanch** [comment]
Buenas tardes, Henry, 

No tengo ese código exacto a mano. Sin embargo, el mismo no tiene demasiados cambios con respecto a un proyecto recién creado. No te tomará mucho tiempo recrearlo.

Saludos!

**Comment by henrypandales** [comment]
Así es lo implemente, y funcionó  
Mil gracias, 

Mi Whatsapp es +57 3147754208
